spring:
  datasource:
    url: jdbc:mysql://db:3306/fintech
    username: root
    password: rootpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
server:
  port: 8080
